export const notificationsData = [
  { id: "@user123", date: "Today", smallMsg: "Registered", longMsg: "use123 has added a new register", time: "1m ago" },
  { id: "@user123", date: "Today", smallMsg: "Registered", longMsg: "use123 has added a new register", time: "1m ago" },
  { id: "@user123", date: "Yesterday", smallMsg: "Registered", longMsg: "use123 has added a new register", time: "1m ago" },
  { id: "@user123", date: "Yesterday", smallMsg: "Registered", longMsg: "use123 has added a new register", time: "1m ago" },
  { id: "@user123", date: "Yesterday", smallMsg: "Registered", longMsg: "use123 has added a new register", time: "1m ago" },
  { id: "@user123", date: "Yesterday", smallMsg: "Registered", longMsg: "use123 has added a new register", time: "1m ago" },
  { id: "@user123", date: "Yesterday", smallMsg: "Registered", longMsg: "use123 has added a new register", time: "1m ago" },
  { id: "@user123", date: "Yesterday", smallMsg: "Registered", longMsg: "use123 has added a new register", time: "1m ago" },
  { id: "@user123", date: "Yesterday", smallMsg: "Registered", longMsg: "use123 has added a new register", time: "1m ago" },
  { id: "@user123", date: "Yesterday", smallMsg: "Registered", longMsg: "use123 has added a new register", time: "1m ago" },
  { id: "@user123", date: "Yesterday", smallMsg: "Registered", longMsg: "use123 has added a new register", time: "1m ago" },
  { id: "@user123", date: "Yesterday", smallMsg: "Registered", longMsg: "use123 has added a new register", time: "1m ago" },
  { id: "@user123", date: "Yesterday", smallMsg: "Registered", longMsg: "use123 has added a new register", time: "1m ago" },
  { id: "@user123", date: "Yesterday", smallMsg: "Registered", longMsg: "use123 has added a new register", time: "1m ago" },
  { id: "@user123", date: "Yesterday", smallMsg: "Registered", longMsg: "use123 has added a new register", time: "1m ago" },
  { id: "@user123", date: "Yesterday", smallMsg: "Registered", longMsg: "use123 has added a new register", time: "1m ago" },
  { id: "@user123", date: "Yesterday", smallMsg: "Registered", longMsg: "use123 has added a new register", time: "1m ago" },
  { id: "@user123", date: "Yesterday", smallMsg: "Registered", longMsg: "use123 has added a new register", time: "1m ago" },
  { id: "@user123", date: "Yesterday", smallMsg: "Registered", longMsg: "use123 has added a new register", time: "1m ago" },
  { id: "@user123", date: "Yesterday", smallMsg: "Registered", longMsg: "use123 has added a new register", time: "1m ago" },
  { id: "@user123", date: "Yesterday", smallMsg: "Registered", longMsg: "use123 has added a new register", time: "1m ago" },
]